### register
POST http://localhost:5000/api/v1/accounts/register
Content-Type: application/json

{
    "firstName": "goof",
    "lastName": "doctor",
    "phoneNumber": "0778976544",
    "email": "goof@owner.com",
    "role": "owner",
    "password":"1212121221",
    "confirmPassword":"1212121221"
}


### login
POST http://localhost:5000/api/v1/accounts/login
Content-Type: application/json

{

    "email": "goof@owner.com",
    "password":"1212121221"
}