### register
POST http://localhost:5000/api/v1/accounts/register
Content-Type: application/json

{
    "firstName": "goof",
    "lastName": "doctor",
    "phoneNumber": "0778976544",
    "email": "goof@owner.com",
    "role": "owner",
    "password":"1212121221",
    "confirmPassword":"1212121221"
}

### register admin
POST http://localhost:5000/api/v1/accounts/register
Content-Type: application/json

{
    "email": "admin@admin.com",
    "firstName": "admin",
    "lastName": "admin",
    "password": "1234567789",
    "confirmPassword":"1234567789",
   "role":"admin",
    "phoneNumber": "0712382367"
}


### login
POST http://localhost:5000/api/v1/accounts/login
Content-Type: application/json

{

    "email": "goof@owner.com",
    "password":"1212121221"
}


### login owner
POST http://localhost:5000/api/v1/accounts/login
Content-Type: application/json

{

    "email": "sunday@owner.com",
    "password":"12345678yh"
}


### logi admin
POST http://localhost:5000/api/v1/accounts/login
Content-Type: application/json

{

    "email": "admin@admin.com",
    "password":"12345678yh"
}

### get all
GET http://localhost:5000/api/v1/accounts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZmlyc3ROYW1lIjoiYWRtaW4iLCJsYXN0TmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJyb2xlIjoiYWRtaW4iLCJpc1ZlcmlmaWVkIjpmYWxzZSwiaWF0IjoxNjA2MTU4MDkwLCJleHAiOjE2MDYxNjg4OTB9.o7npZt_wsUvvGiLW7Bu08zhzxKmM9I3enQ2X48m1b9U