### get company menu by id
POST https://wissenspos.herokuapp.com/api/v1/company/2/menu/2/category
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZmlyc3ROYW1lIjoic3VuZGF5IiwibGFzdE5hbWUiOiJvd25lciIsImVtYWlsIjoic3VuZGF5QG93bmVyLmNvbSIsInBob25lTnVtYmVyIjoiMDcxMjM4MjM2NiIsInBhc3N3b3JkIjoiJDJiJDEwJC5pM1pYZ3hVRUFMa3VJc0hkT1FKZC5Pd0VnOE5tUjFod2UxZzU1dlBwZm9LZjNMdlg3cTNtIiwicm9sZSI6Im93bmVyIiwiYWN0aXZlIjp0cnVlLCJ2ZXJpZmllZCI6bnVsbCwiaXNWZXJpZmllZCI6ZmFsc2UsInZlcmlmaWNhdGlvblRva2VuIjpudWxsLCJpbWFnZV91cmwiOm51bGwsImNyZWF0ZWRfYXQiOiIyMDIwLTExLTI1VDE3OjM4OjEwLjA2MloiLCJ1cGRhdGVkX2F0IjoiMjAyMC0xMS0yNVQxNzozODoxMC4wNjJaIiwiZGVsZXRlZF9hdCI6bnVsbCwiaWF0IjoxNjEwNjc3MDM1LCJleHAiOjE2MTA2ODc4MzV9.849j7tEMyrGSwS0Tg6TpxP-A1dg5bUg0D1VJinQ4-JE

{
    "name":"lunch1",
    "menu_id":1
}