### get all companies
GET http://localhost:5000/api/v1/company/mine
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDgsImZpcnN0TmFtZSI6InN1bmRheSIsImxhc3ROYW1lIjoib3duZXIiLCJlbWFpbCI6InN1bmRheUBvd25lci5jb20iLCJwaG9uZU51bWJlciI6IjA3MTIzODIzNjYiLCJwYXNzd29yZCI6IiQyYiQxMCRycVVoRkg3MzV6a2VSV05Ud1FiQUZlLmZJbXZObms0dk5pOVY4dTJrdFpyWUhYM0V5dUMuTyIsInJvbGUiOiJvd25lciIsImFjdGl2ZSI6dHJ1ZSwidmVyaWZpZWQiOm51bGwsImlzVmVyaWZpZWQiOmZhbHNlLCJ2ZXJpZmljYXRpb25Ub2tlbiI6bnVsbCwiaW1hZ2VfdXJsIjpudWxsLCJjcmVhdGVkX2F0IjoiMjAyMS0wMS0xNVQwMjowMTo0Mi43NDlaIiwidXBkYXRlZF9hdCI6IjIwMjEtMDEtMTVUMDI6MDE6NDIuNzQ5WiIsImRlbGV0ZWRfYXQiOm51bGwsImlhdCI6MTYxMDY3NjE3MiwiZXhwIjoxNjEwNjg2OTcyfQ.46zvq9faDhFVPzZBNZLlmV972zdRPVg-dVVvgIQu-Tk


### get company menu by id
GET http://localhost:5000/api/v1/company/17/menu


### get company menu by id
GET http://localhost:5000/api/v1/company/17/menu/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDgsImZpcnN0TmFtZSI6InN1bmRheSIsImxhc3ROYW1lIjoib3duZXIiLCJlbWFpbCI6InN1bmRheUBvd25lci5jb20iLCJwaG9uZU51bWJlciI6IjA3MTIzODIzNjYiLCJwYXNzd29yZCI6IiQyYiQxMCRycVVoRkg3MzV6a2VSV05Ud1FiQUZlLmZJbXZObms0dk5pOVY4dTJrdFpyWUhYM0V5dUMuTyIsInJvbGUiOiJvd25lciIsImFjdGl2ZSI6dHJ1ZSwidmVyaWZpZWQiOm51bGwsImlzVmVyaWZpZWQiOmZhbHNlLCJ2ZXJpZmljYXRpb25Ub2tlbiI6bnVsbCwiaW1hZ2VfdXJsIjpudWxsLCJjcmVhdGVkX2F0IjoiMjAyMS0wMS0xNVQwMjowMTo0Mi43NDlaIiwidXBkYXRlZF9hdCI6IjIwMjEtMDEtMTVUMDI6MDE6NDIuNzQ5WiIsImRlbGV0ZWRfYXQiOm51bGwsImlhdCI6MTYxMDY3ODYyMSwiZXhwIjoxNjEwNjg5NDIxfQ.lk7gwD0hFXN80xwYXB9FFv_YHVC3NonlwuaY6Q0SMpM

### get company menu by id
GET https://wissenspos.herokuapp.com/api/v1/company/2/menu/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDEsImZpcnN0TmFtZSI6ImFkbWluIiwibGFzdE5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwicGhvbmVOdW1iZXIiOiIwNzEyMzgyMzY4IiwicGFzc3dvcmQiOiIkMmIkMTAkaEowTVVWSVZGUkwuNG1SZFpLMW4wT1poOWlzb2g2aDBtZ2dCMVMzMzFSN0Ruai5QYzUyMXEiLCJyb2xlIjoiYWRtaW4iLCJhY3RpdmUiOmZhbHNlLCJ2ZXJpZmllZCI6bnVsbCwiaXNWZXJpZmllZCI6ZmFsc2UsInZlcmlmaWNhdGlvblRva2VuIjpudWxsLCJpbWFnZV91cmwiOm51bGwsImNyZWF0ZWRfYXQiOiIyMDIxLTAxLTA0VDExOjU0OjEwLjk2MFoiLCJ1cGRhdGVkX2F0IjoiMjAyMS0wMS0wNFQxMTo1NDoxMC45NjBaIiwiZGVsZXRlZF9hdCI6bnVsbCwiaWF0IjoxNjA5NzYxMzkyLCJleHAiOjE2MDk3NzIxOTJ9.ds0K0NDuEAc4r2M9iouC6eDJsSbSnlsXjbr8rgsLej8
