### get all companies
GET http://localhost:5000/api/v1/company/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDEsImZpcnN0TmFtZSI6ImFkbWluIiwibGFzdE5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwicGhvbmVOdW1iZXIiOiIwNzEyMzgyMzY4IiwicGFzc3dvcmQiOiIkMmIkMTAkaEowTVVWSVZGUkwuNG1SZFpLMW4wT1poOWlzb2g2aDBtZ2dCMVMzMzFSN0Ruai5QYzUyMXEiLCJyb2xlIjoiYWRtaW4iLCJhY3RpdmUiOmZhbHNlLCJ2ZXJpZmllZCI6bnVsbCwiaXNWZXJpZmllZCI6ZmFsc2UsInZlcmlmaWNhdGlvblRva2VuIjpudWxsLCJpbWFnZV91cmwiOm51bGwsImNyZWF0ZWRfYXQiOiIyMDIxLTAxLTA0VDExOjU0OjEwLjk2MFoiLCJ1cGRhdGVkX2F0IjoiMjAyMS0wMS0wNFQxMTo1NDoxMC45NjBaIiwiZGVsZXRlZF9hdCI6bnVsbCwiaWF0IjoxNjA5NzYxMzkyLCJleHAiOjE2MDk3NzIxOTJ9.ds0K0NDuEAc4r2M9iouC6eDJsSbSnlsXjbr8rgsLej8