version: "3.1"
services:
    db:
        image: postgres:10
        restart: always
        volumes:
            - ./docker-data/db-data:/var/lib/postgresql/data/wissenpos-data
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - 5433:5432 #host:container
    adminer: #admin console for the db
        depends_on:
            - db
        image: adminer
        restart: always
        ports:
            - 8082:8080
# volumes:
#   db-data: {}
