version: "3.1"
services: 
    node-wissenpos-service:
        build:
            context: .
            args: 
                NODE_ENV: development
        ports:
            - 5000:5000
        volumes: 
            - .:/usr/src/app # bind mount
            - /usr/src/app/node_modules # anonymous volume
        environment: 
            - NODE_ENV=development
        command: npm run dev                    