version: "3"
services:
  nginx:
    ports:
      - "80:80"
  node-store-service:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    # env_file:
    #   - ./.env.dev
    command: npm start