version: 2.1
executors:
    node-executor:
        docker:
            - image: circleci/node:11.10.1
    postgres-executor:
        docker:
            - image: postgres:10
    docker-executor:
        docker:
            - image: docker:18.06.3-ce-git

jobs:
    dependencies: # reusable jobs
        executor: node-executor
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-npm-deps-{{ checksum "package-lock.json" }}
            - run:
                  name: Install dependencies
                  command: yarn install --silent
            - save_cache:
                  key: v1-npm-deps-{{ checksum "package-lock.json" }}
                  paths:
                      - node_modules
            - persist_to_workspace:
                  root: .
                  paths:
                      - .

    build_docker_image: #reusable build jobs for docker
        executor: docker-executor
        steps:
            - attach_workspace:
                  at: .
            - run:
                  name: Build app docker image and push
                  command: |
                      docker build -t sundaypriest/wissenpos-backend .
                      docker login -u $DOCKER_LOGIN -p $DOCKER_PWD
                      docker push sundaypriest/wissenpos-backend:latest
    build-and-test: # build app and test
        executor: node-executor
        steps:
            - attach_workspace:
                  at: .
            - run: yarn test

    deploy-to-test: # deploy safe code to development
        executor: node-executor
        steps:
            - attach_workspace:
                  at: .
            - run:
                  name: Deploy to heroku
                  command: |
                      git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master -f
workflows:
    version: 2
    wissenpos-backend-workflows:
        jobs:
            - dependencies
            # will figure setting this out on circle-ci
            # - build-and-test:
            #       requires:
            #           - dependencies
            #       filters:
            #           branches:
            #               only:
            #                   - /feature.*/

            - build_docker_image:
                  context: dev_context
                  filters:
                      branches:
                          only:
                              - develop
                              - /feature.*/
                  requires:
                      - deploy-to-test

            - deploy-to-test:
                  context: dev_context
                  filters:
                      branches:
                          only:
                              - develop
                              - /feature.*/
                  requires:
                      - dependencies
