module.exports = {
    user: "user",
    customer: "customer",
    address: "address",
    company: "company",
    accounts: "accounts",
    category: "category",
    menu: "menu",
    menuCategory: "menuCategory",
    item: "item",
    menuItem: "menuItem",
    order: "order",
    orderItem: "orderItem",
    payments: "payments",
};
